id: I29B26E40
ocr_import_info:
  timestamp: '2023-08-15T02:12:35.544948+00:00'
  batch_id: batch-b58f
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Tenzin Jordhen
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-08-15 02:44:16.645682+00:00
last_modified: 2023-08-15 02:44:16.645688+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W00KG01606
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW00KG01606
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མདོ་ཀུན་ལས་བསྟུས་པའི་དོན་བསྡུས་པ།
  languages:
  - bo
  author: རྒྱ་ལོ་ཙཱ་བ་བརྩོན་འགྲུས་སེངྒེ
statistics:
  ocr_word_mean_confidence_index: 0.9232561338248848
  ocr_word_median_confidence_index: 0.97915834
bases:
  I00KG02852:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG02852
      total_pages: 14
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG02852.txt
    statistics:
      ocr_word_median_confidence_index: 0.97915834
      ocr_word_mean_confidence_index: 0.9232561338248848
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
